version: '3.9'

services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    volumes:
      - ./policies:/policies
    command:
      - "run"
      - "--server"
      - "--log-level=info"
      - "/policies"
  proxy:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "18000:18000"